# **Notebook 1 – Dataset Understanding**

## **Dataset Selection and Overview**

**Dataset Name :** IBM Telco Customer Churn Dataset

**Dataset Source :** https://www.kaggle.com/datasets/yeanzc/telco-customer-churn-ibm-dataset

**Business/Domain :** Telecommunications and Customer Retention

**Number of Rows :** 7043 rows

**Number of Columns :** 33 columns



**Data Description :**

| Column | Description |
|---|---|
| **CustomerID** | Unique ID for each customer |
| **Count** | Used to count customers |
| **Country** | Customer's country |
| **State** | Customer's state |
| **City** | Customer's city |
| **Zip Code** | Customer's zip code |
| **Lat Long** | Customer's latitude and longitude |
| **Latitude** | Location latitude |
| **Longitude** | Location longitude |
| **Gender** | Male or Female |
| **Senior Citizen** | Whether the customer is 65 or older |
| **Partner** | Whether the customer has a partner |
| **Dependents** | Whether the customer has dependents |
| **Tenure Months** | Number of months with the company |
| **Phone Service** | Whether the customer uses phone service |
| **Multiple Lines** | Whether the customer uses multiple phone lines |
| **Internet Service** | Type of internet service |
| **Online Security** | Whether the customer uses online security |
| **Online Backup** | Whether the customer uses online backup |
| **Device Protection** | Whether the customer has device protection |
| **Tech Support** | Whether the customer uses tech support |
| **Streaming TV** | Whether the customer streams TV |
| **Streaming Movies** | Whether the customer streams movies |
| **Contract** | Customer's contract type |
| **Paperless Billing** | Whether the customer uses paperless billing |
| **Payment Method** | Customer's payment method |
| **Monthly Charge** | Customer's monthly charges |
| **Total Charges** | Total charges paid by the customer |
| **Churn Label** | Whether the customer left or stayed |
| **Churn Value** | `1` for churn and `0` for no churn |
| **Churn Score** | Customer's predicted churn score from 0–100 |
| **CLTV** | Customer Lifetime Value |
| **Churn Reason** | Reason why the customer left |

**Important Columns**

| Column | Description |
|---|---|
| `customerID` | Unique customer ID |
| `tenure` | Number of months with the company |
| `Contract` | Type of customer contract |
| `MonthlyCharges` | Monthly amount charged |
| `TotalCharges` | Total amount charged |
| `Churn` | Whether the customer left the company |

**Target Variable**

`Churn`

- `Yes` – Customer left the company
- `No` – Customer stayed with the company

**Why I Selected This Dataset**

This dataset contains both numerical and categorical data. It is suitable for all Sprint 4 EDA topics and can later be used to build a machine learning model to predict customer churn.

In [1]:
# Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# Dataset from kaggle
import kagglehub
path = kagglehub.dataset_download("yeanzc/telco-customer-churn-ibm-dataset")
print("Path to dataset files:", path)

Downloading to C:\Users\iamna\.cache\kagglehub\datasets\yeanzc\telco-customer-churn-ibm-dataset\1.archive...

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.25M/1.25M [00:01<00:00, 812kB/s]

Extracting files...
Path to dataset files: C:\Users\iamna\.cache\kagglehub\datasets\yeanzc\telco-customer-churn-ibm-dataset\versions\1

In [4]:
# View files in the downloaded dataset
import os
os.listdir(path)

['Telco_customer_churn.xlsx']

In [11]:
# Load dataset
df = pd.read_excel(path + "/Telco_customer_churn.xlsx")

## **1. What is a Dataset?**

**Understand the Concept**

A dataset is a collection of related data organized in rows and columns.

- Each row represents one observation or record.
- Each column represents a specific attribute or feature.

**Demonstrate the Concept**

**Real-Life Example**

A telecom company stores customer details like Customer ID, Gender, Contract Type, Monthly Charges, and Churn Status. All these details together form a dataset.

**AI/ML Usage**

- In Machine Learning, datasets are used to find patterns and train models.
- our dataset can help predict whether a customer may leave the company.

In [12]:
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

**Interpretation**

- The dataset is loaded into the DataFrame df.
- Each row represents one customer.
- Each column contains information about the customer.

## **2. What is a Feature?**

**Understand the Concept**

- A feature is a column in a dataset that provides information about each record.
- For example, Gender, Tenure Months, and Monthly Charge are features in our dataset.

**Demonstrate the Concept**

**Real-Life Example**

- A telecom company collects customer information such as gender, contract type, tenure, and monthly charges.
- Each of these details is a feature.

**AI/ML Usage**

- Features are used as input data for Machine Learning models.
- customer features can be used to predict whether a customer will leave the company.

In [13]:
# show all columns name
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

**Interpretation**

- Each column represents a feature.
- Features contain different information about customers.

## **3. What is a Target?**



**Understand the Concept**

A target is the value that we want to predict using other features in a dataset.

**Demonstrate the Concept**

In our Telecom Customer Churn dataset, Churn Label tells us whether a customer left or stayed with the company.

**Real-Life Example**

A telecom company wants to predict whether a customer will leave the company.

**AI/ML Usage**

- In Machine Learning, the target is the output that the model tries to predict.
- For this dataset, Churn Label can be used as the target for a customer churn prediction model.

In [14]:
# Churn Label column
df["Churn Label"].head()

0    Yes
1    Yes
2    Yes
3    Yes
4    Yes
Name: Churn Label, dtype: object

**Interpretation**

- Churn Label is the target column in our dataset.
- It shows whether a customer left or stayed.
- Other features can be used to predict the Churn Label.

## **4. Independent Variables**



**Understand the Concept**

Independent variables are the input features used to predict the target variable.

**Demonstrate the Concept**

**Real-Life Example**

- A telecom company can use customer details to predict whether a customer may leave the company.
- Tenure Months, Contract, and Monthly Charge can affect customer churn.



**AI/ML Usage**

- Independent variables are used as input for Machine Learning models.
- The model uses these variables to predict the target.

In [16]:
# Independent variables
independent_variables = df[["Gender", "Tenure Months", "Contract", "Monthly Charges"]]
independent_variables.head()

   Gender  Tenure Months        Contract  Monthly Charges
0    Male              2  Month-to-month            53.85
1  Female              2  Month-to-month            70.70
2  Female              8  Month-to-month            99.65
3  Female             28  Month-to-month           104.80
4    Male             49  Month-to-month           103.70

**Interpretation**

- Independent variables are used as input data.
- They can be used to predict the target variable.

## **5. Dependent Variables**



**Understand the Concept**

* A dependent variable is the output variable.
* Its value depends on one or more independent variables.

**Demonstrate the Concept**

In our dataset Churn Label is the dependent variable.

It depends on customer details such as Tenure Months, Contract, Monthly Charge, Internet Service

**Real-Life Example:**

* A telecom company wants to know whether a customer will leave.
* Customer details can affect the customer's decision to stay or leave.
* Customer churn is the dependent variable.

**AI/ML Usage:**

* The dependent variable is used as the target variable in Machine Learning.
* The model learns from independent variables to predict the dependent variable.

In [17]:
# Dependent variable
dependent_variable = df["Churn Label"]
dependent_variable.head()

0    Yes
1    Yes
2    Yes
3    Yes
4    Yes
Name: Churn Label, dtype: object

**Interpretation**

* Churn Label is the dependent variable.
* It can be predicted using independent variables.

## **6. Numerical Features**



**Understand the Concept**

* Numerical features contain numbers.
* They represent values that can be measured or counted.


**Demonstrate the Concept**

**Example**

* In our dataset, Tenure Months, Monthly Charge, and Total Charges are numerical features.
* These columns contain numerical values.


**AI/ML Usage:**

* Numerical features can be used as input for Machine Learning models.
* They help the model identify patterns and make predictions.

In [18]:
# Select numerical features
numerical_features = df.select_dtypes(include='number')
numerical_features.head()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
0,1,90003,33.964131,-118.272783,2,53.85,1,86,3239
1,1,90005,34.059281,-118.307420,2,70.70,1,67,2701
2,1,90006,34.048013,-118.293953,8,99.65,1,86,5372
3,1,90010,34.062125,-118.315709,28,104.80,1,84,5003
4,1,90015,34.039224,-118.266293,49,103.70,1,89,5340

**Interpretation**

* The selected columns contain numerical values.
* They provide measurable information about customers.

## **7. Categorical Features**



**Understand the Concept**

Categorical features contain values that belong to different groups or categories.

**Demonstrate the Concept**

**Real-Life Example**

A customer's contract can be Month-to-Month, One Year, or Two Year. These values represent different categories.

**AI/ML Usage**

- Categorical features can be used as input data for Machine Learning models.
- They are usually converted into numerical form before training a model.

In [21]:
# Categorical features
categorical_features = df.select_dtypes(include='object')  
categorical_features.head(2)

,CustomerID,Country,State,City,Lat Long,Gender,Senior Citizen,Partner,Dependents,Phone Service,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Total Charges,Churn Label,Churn Reason
0,3668-QPYBK,United States,California,Los Angeles,"33.964131, -118.272783",Male,No,No,No,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,108.15,Yes,Competitor made better offer
1,9237-HQITU,United States,California,Los Angeles,"34.059281, -118.30742",Female,No,No,Yes,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,151.65,Yes,Moved

**Interpretation**

- These columns contain category-based values.
- Each value belongs to a specific group.

## **8. Discrete Features**



**Understand the Concept**

Discrete features contain countable values, usually whole numbers.

**Demonstrate the Concept**

The values have separate and fixed counts. They usually do not contain decimal values.


**Real-Life Example**

The number of dependents of a customer can be 0, 1, 2, or 3. It cannot normally be 1.5.

**AI/ML Usage**

Discrete features can be used as input features to find patterns and make predictions.

In [24]:
# Discrete Features -Dependents column
df["Dependents"].value_counts()

Dependents
No     5416
Yes    1627
Name: count, dtype: int64

**Interpretation**

- Dependents contains countable values.
- Each customer can have a specific number of dependents.

## **9. Continuous Features**



**Understand the Concept**

Continuous features can have any value within a range, including decimal values.

**Demonstrate the Concept**

These values are usually measured and can contain decimal points.

**Real-Life Example**

A customer's monthly charge can be 50.25, 75.50, or 100.75. These values can vary within a range.

**AI/ML Usage**

Continuous features can be used as input features to analyze patterns and build Machine Learning models.

In [26]:
#  Continuous - Monthly Charge column
df["Monthly Charges"].head()

0     53.85
1     70.70
2     99.65
3    104.80
4    103.70
Name: Monthly Charges, dtype: float64

**Interpretation**

- Monthly Charge is a continuous feature.
- It can contain different values, including decimals.

## **10. Identifier Columns**



**Understand the Concept**

Identifier columns are used to uniquely identify each record in a dataset.

**Demonstrate the Concept**

In our dataset, CustomerID is an identifier column. Each customer has a unique ID.



**Real-Life Example**

A telecom company gives each customer a unique CustomerID to identify and manage their details.

**AI/ML Usage**

Identifier columns are usually not useful for prediction because each value is unique. They are mainly used to identify records.

In [27]:
# Identifier Columns - check unique values in CustomerID
df["CustomerID"].nunique()

7043

**Interpretation**

- CustomerID is used to uniquely identify each customer.
- Each customer should have a unique ID.

## **11. Target Variable**



**Understand the Concept**

A target variable is the output variable that we want to predict.

**Demonstrate the Concept**

**Real-Life Example**

A telecom company wants to predict whether a customer will leave the company. Here, Churn Label is the target variable.

**AI/ML Usage**

- Machine Learning models learn from input features to predict the target variable. 
- In this dataset, the model can predict customer churn.

In [28]:
# Target Variable 
df["Churn Label"].head()

0    Yes
1    Yes
2    Yes
3    Yes
4    Yes
Name: Churn Label, dtype: object

**Interpretation**

- Churn Label is the target variable.
- It shows whether a customer left or stayed.
- It can be predicted using customer-related features.

## **12. Metadata**



**Understand the Concept**

Metadata is information that describes a dataset.

**Demonstrate the Concept**

Metadata can include the dataset name, number of rows, number of columns, column names, and data types.

**Real-Life Example**

For our Telecom Customer Churn dataset:

- Dataset name: Telecom Customer Churn Dataset
- Number of rows: 7,043
- Number of columns: 33
- Target variable: Churn Label

These details are metadata about the dataset.

**AI/ML Usage**

Metadata helps us understand the dataset before starting data analysis or building a Machine Learning model.

In [29]:
# Metadata - dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

**Interpretation**

- The output shows information about the dataset.
- It includes column names, data types, and non-null values.
- This information helps us understand the dataset structure.

## **13. Dataset Dimensions**



**Understand the Concept**

Dataset dimensions show the number of rows and columns in a dataset.

**Demonstrate the Concept**

Our dataset contains 7,043 rows and 33 columns.

**AI/ML Usage**

Dataset dimensions help us understand the size and structure of the data before analysis and Machine Learning.

In [30]:
# Dataset Dimensions - dataset dimensions
df.shape

(7043, 33)

**Interpretation**

- The dataset contains 7,043 rows.
- The dataset contains 33 columns.
- Each row represents one customer.
- Each column represents customer information.