# **Notebook 3 – Data Quality Assessment**

## **Dataset Information**

Dataset Name: Employee Data Quality Dataset

Dataset Source: Kaggle

Business/Domain: Human Resources

Number of Rows: 1,000

Number of Columns: 12

**Dataset Overview**

| Column Name | Short Description |
|---|---|
| EmployeeID | Unique identifier for each employee |
| Name | Name of the employee |
| Age | Age of the employee |
| Gender | Gender of the employee |
| Department | Department where the employee works |
| Salary | Monthly salary of the employee |
| Experience | Years of work experience |
| JoiningDate | Date when the employee joined |
| PerformanceScore | Employee performance score |
| Email | Employee email address |
| City | City where the employee works |
| Status | Current employment status |

**Why This Dataset Was Selected**

It contains realistic employee data along with intentional data issues that can be identified and analyzed using Pandas.

In [34]:
# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
# Load dataset
df = pd.read_csv("Employee_Data_Quality_Dataset.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeID        1000 non-null   object
 1   Name              997 non-null    object
 2   Age               995 non-null    object
 3   Gender            1000 non-null   object
 4   Department        995 non-null    object
 5   Salary            997 non-null    object
 6   Experience        1000 non-null   object
 7   JoiningDate       1000 non-null   object
 8   PerformanceScore  1000 non-null   int64
 9   Email             998 non-null    object
 10  City              996 non-null    object
 11  Status            999 non-null    object
dtypes: int64(1), object(11)
memory usage: 93.9+ KB

## **1. Missing Values**


**Understand the Concept**

Missing values are data values that are not available in a dataset.

**Demonstrate the Concept**

Missing values can appear as empty cells or null values.

**Real-Life Example**

An employee dataset may have missing values if an employee's age, salary, department, or email is not recorded.

**AI/ML Usage**

Missing values can affect data analysis and Machine Learning models. They should be identified before preprocessing.

## **1.1 Number of Missing Values**



**Understand the Concept**

The number of missing values shows how many data values are missing in the dataset.

**Demonstrate the Concept**

We can count all missing values to understand the overall amount of missing data.


**Real-Life Example**

An employee dataset may have missing values in Age, Salary, Department, City, or Email.

**AI/ML Usage**

Knowing the total number of missing values helps us decide whether the missing data should be removed, filled, or handled in another way.

In [36]:
# no of missing values
df.isnull().sum()

EmployeeID          0
Name                3
Age                 5
Gender              0
Department          5
Salary              3
Experience          0
JoiningDate         0
PerformanceScore    0
Email               2
City                4
Status              1
dtype: int64

In [37]:
# total no of missing values
df.isnull().sum().sum()

np.int64(23)

**Interpretation**

- The output shows the total number of missing values in the dataset.
- This helps us understand the overall amount of missing data.

## **1.2. Percentage of Missing Values**



**Understand the Concept**

The percentage of missing values shows how much data is missing compared to the total data.

**Demonstrate the Concept**

It helps us understand the amount of missing data in each column as a percentage.

**Real-Life Example**

If 10 values are missing out of 1,000 records, the missing value percentage is 1%.

**AI/ML Usage**

The missing value percentage helps us decide whether to remove, fill, or keep missing data during preprocessing.

In [38]:
# missing value percentage for each column
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

EmployeeID          0.0
Name                0.3
Age                 0.5
Gender              0.0
Department          0.5
Salary              0.3
Experience          0.0
JoiningDate         0.0
PerformanceScore    0.0
Email               0.2
City                0.4
Status              0.1
dtype: float64

**Interpretation**

- The output shows the percentage of missing values in each column.
- A higher percentage means more data is missing in that column.

## **1.3 Missing Values by Column**



**Understand the Concept**

Missing values by column show how many values are missing in each column.

**Demonstrate the Concept**

This helps us identify which columns contain missing data.

**Real-Life Example**

In an employee dataset, Age may have 5 missing values while Salary may have 3 missing values.

**AI/ML Usage**

Checking missing values by column helps us choose the correct method to handle missing data for each feature.

In [39]:
# Missing Values by Column
missing_by_column = df.isnull().sum()
print(missing_by_column)

EmployeeID          0
Name                3
Age                 5
Gender              0
Department          5
Salary              3
Experience          0
JoiningDate         0
PerformanceScore    0
Email               2
City                4
Status              1
dtype: int64

**Interpretation**

- The output shows missing values for each column.
- Columns with 0 have no missing values.
- Columns with values greater than 0 contain missing data.

## **1.4. Missing Value Patterns**



**Understand the Concept**

Missing value patterns show how missing values are distributed in a dataset.

**Demonstrate the Concept**

It helps us check whether missing values appear in the same rows or different columns.

**Real-Life Example**

An employee may have both Age and Salary missing, while another employee may only have the Email missing.

**AI/ML Usage**

Missing value patterns help us understand the relationship between missing values and choose a suitable preprocessing method.

In [40]:
# Missing Value Patterns 
missing_rows = df[df.isnull().any(axis=1)]
missing_rows

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
10,EMP10011,Arun Singh,NaN,Male,Finance,61924.34,9.5,2019-08-26,1,arun.singh10@company.com,Chennai,Active
15,EMP10016,Naveen Kumar,56.0,Female,IT,NaN,9.6,2017-01-03,5,naveen.kumar15@company.com,Chennai,Inactive
25,EMP10026,Arun Patel,NaN,Male,Marketing,72754.51,1.8,2019-01-01,3,arun.patel25@company.com,Coimbatore,On Leave
30,EMP10031,Bala Iyer,54.0,Female,NaN,62769.34,18.1,2022-01-11,4,bala.iyer30@company.com,Coimbatore,On Leave
40,EMP10041,Bala Kumar,29.0,Male,Sales,84958.17,27.8,2015-12-15,1,bala.kumar40@company.com,NaN,Inactive
50,EMP10051,Kavin Reddy,NaN,Male,HR,81129.16,1.1,2018-10-06,3,kavin.reddy50@company.com,Mumbai,Active
60,EMP10061,Meena Khan,31.0,Male,IT,NaN,31.0,2018-10-26,3,meena.khan60@company.com,Pune,Inactive
70,EMP10071,Naveen Reddy,41.0,Female,Operations,103513.46,11.2,2025-03-17,4,NaN,Pune,Active
90,EMP10091,Rahul Reddy,26.0,Male,NaN,83274.44,14.6,2022-02-27,5,rahul.reddy90@company.com,Coimbatore,On Leave
100,EMP10101,Sanjay Nair,NaN,Female,Sales,82768.35,22.3,2025-03-02,4,sanjay.nair100@company.com,Chennai,Active
120,EMP10121,Divya Reddy,32.0,Female,IT,NaN,28.6,2015-08-06,3,divya.reddy120@company.com,Pune,On Leave
140,EMP10141,Vijay Kumar,34.0,Female,IT,38216.04,3.5,2015-08-28,3,vijay.kumar140@company.com,NaN,On Leave
150,EMP10151,Meena Sharma,NaN,Female,HR,64389.29,3.0,2022-01-07,1,meena.sharma150@company.com,Chennai,Active
170,EMP10171,Bala Patel,38.0,Female,Sales,64783.2,13.4,2024-02-28,3,NaN,Bengaluru,On Leave
200,EMP10201,Bala Nair,49.0,Female,NaN,70284.3,1.6,2016-12-10,1,bala.nair200@company.com,Coimbatore,Active
210,EMP10211,NaN,51.0,Female,Finance,26750.63,15.1,2016-12-28,5,vijay.reddy210@company.com,Chennai,On Leave
211,EMP10212,NaN,50.0,Male,Sales,99936.66,6.1,2018-02-04,3,kavin.nair211@company.com,Coimbatore,Inactive
212,EMP10213,NaN,38.0,Female,Operations,98243.51,24.8,2020-01-22,2,naveen.iyer212@company.com,Bengaluru,Active
220,EMP10221,Sanjay Raj,39.0,Female,Operations,107114.03,16.6,2022-12-14,1,sanjay.raj220@company.com,NaN,Inactive
221,EMP10222,Naveen Iyer,38.0,Male,Marketing,33660.63,5.4,2025-02-20,3,naveen.iyer221@company.com,NaN,Inactive
230,EMP10231,Priya Reddy,59.0,Female,NaN,78916.38,24.1,2016-02-10,4,priya.reddy230@company.com,Chennai,Inactive
231,EMP10232,Naveen Patel,32.0,Female,NaN,36800.9,31.4,2023-06-09,1,naveen.patel231@company.com,Coimbatore,On Leave
233,EMP10234,Naveen Sharma,41.0,Female,Marketing,77535.14,20.9,2020-10-03,1,naveen.sharma233@company.com,Chennai,NaN

**Interpretation**

- The output displays rows that contain at least one missing value.
- We can check whether multiple columns have missing values in the same row.

## **2. Duplicate Records**



**Understand the Concept**

Duplicate records are rows that appear more than once in a dataset.

**AI/ML Usage**

Duplicate records can affect data analysis and Machine Learning models. They should be identified before preprocessing.

## **2.1. Identify Duplicates**



**Understand the Concept**

Identifying duplicates means finding rows that are repeated in a dataset.

**Demonstrate the Concept**

The duplicated() function checks whether a row already appears earlier in the dataset.


**Real-Life Example**

The same employee record may be entered more than once by mistake.

**AI/ML Usage**

Duplicate records can affect data analysis and Machine Learning results. They should be identified before preprocessing.

In [41]:
# duplicate rows
duplicate_records = df[df.duplicated()]
duplicate_records

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
985,EMP10401,Rahul Das,40.0,Female,IT,107911.61,3.9,2020-05-04,1,rahul.das400@company.com,Chennai,Inactive
986,EMP10402,Kavin Nair,51.0,Male,Finance,29381.74,19.9,2018-09-14,3,kavin.nair401@company.com,Bengaluru,Inactive
987,EMP10403,Meena Das,56.0,Male,Operations,46503.39,25.6,2023-04-27,4,meena.das402@company.com,Coimbatore,Active
988,EMP10404,Rahul Patel,49.0,Female,IT,105965.07,23.4,2020-09-24,5,rahul.patel403@company.com,Hyderabad,On Leave
989,EMP10405,Bala Patel,51.0,Male,Finance,65772.35,9.4,2016-05-21,5,bala.patel404@company.com,Mumbai,Active
990,EMP10406,Divya Nair,41.0,Female,IT,45921.4,17.1,2019-09-09,4,divya.nair405@company.com,Hyderabad,On Leave
991,EMP10407,Priya Iyer,56.0,Male,Sales,103782.25,30.8,2015-08-13,4,priya.iyer406@company.com,Mumbai,On Leave
992,EMP10408,Kavin Khan,33.0,Female,HR,69121.16,4.8,2017-10-20,5,kavin.khan407@company.com,Mumbai,Inactive
993,EMP10409,Bala Khan,43.0,Male,HR,82673.51,22.1,2018-09-19,4,bala.khan408@company.com,Chennai,On Leave
994,EMP10410,Vijay Iyer,28.0,Female,IT,37510.88,8.2,2017-06-12,2,vijay.iyer409@company.com,Coimbatore,Inactive
995,EMP10411,Bala Singh,45.0,Male,Operations,82061.85,26.0,2015-08-23,1,bala.singh410@company.com,Mumbai,Inactive
996,EMP10412,Sanjay Nair,39.0,Female,HR,59376.04,16.5,2024-11-08,3,sanjay.nair411@company.com,Hyderabad,Active
997,EMP10413,Rahul Khan,22.0,Female,HR,67794.2,16.6,2017-08-14,3,rahul.khan412@company.com,Mumbai,Inactive
998,EMP10414,Arun Reddy,41.0,Male,Finance,44664.29,18.1,2020-01-14,1,arun.reddy413@company.com,Chennai,On Leave
999,EMP10415,Vijay Raj,29.0,Male,HR,28488.53,3.8,2024-07-21,5,vijay.raj414@company.com,Hyderabad,Inactive

**Interpretation**

- The output displays the duplicate rows.
- Duplicate records are repeated employee records.

## **2.2 Count Duplicates**



**Understand the Concept**

Counting duplicates shows how many duplicate rows are present in a dataset.

**Demonstrate the Concept**

The duplicated() function identifies duplicate rows, and sum() counts them.


**Real-Life Example**

If the same employee record appears multiple times, the repeated rows are counted as duplicates.

**AI/ML Usage**

Duplicate records can affect data analysis and Machine Learning results. Counting them helps us understand the data quality.

In [42]:
# Count duplicate rows
duplicate_count = df.duplicated().sum()
print("No of duplicate rows:", duplicate_count)

No of duplicate rows: 15

**Interpretation**

- The output shows the total number of duplicate rows.

## **2.3 Completely Duplicated Rows**



**Understand the Concept**

Completely duplicated rows are rows where all column values are exactly the same.

**Demonstrate the Concept**

We can compare all columns in each row to find records that are completely repeated.

**Real-Life Example**

If the same employee record, including EmployeeID, Name, Age, Department, and Salary, appears more than once, it is a completely duplicated row.

**AI/ML Usage**

Completely duplicated rows can create repeated information and affect data analysis and Machine Learning results.

In [43]:
# completely duplicated rows
completely_duplicated = df[df.duplicated(keep=False)]
completely_duplicated

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
400,EMP10401,Rahul Das,40.0,Female,IT,107911.61,3.9,2020-05-04,1,rahul.das400@company.com,Chennai,Inactive
401,EMP10402,Kavin Nair,51.0,Male,Finance,29381.74,19.9,2018-09-14,3,kavin.nair401@company.com,Bengaluru,Inactive
402,EMP10403,Meena Das,56.0,Male,Operations,46503.39,25.6,2023-04-27,4,meena.das402@company.com,Coimbatore,Active
403,EMP10404,Rahul Patel,49.0,Female,IT,105965.07,23.4,2020-09-24,5,rahul.patel403@company.com,Hyderabad,On Leave
404,EMP10405,Bala Patel,51.0,Male,Finance,65772.35,9.4,2016-05-21,5,bala.patel404@company.com,Mumbai,Active
405,EMP10406,Divya Nair,41.0,Female,IT,45921.4,17.1,2019-09-09,4,divya.nair405@company.com,Hyderabad,On Leave
406,EMP10407,Priya Iyer,56.0,Male,Sales,103782.25,30.8,2015-08-13,4,priya.iyer406@company.com,Mumbai,On Leave
407,EMP10408,Kavin Khan,33.0,Female,HR,69121.16,4.8,2017-10-20,5,kavin.khan407@company.com,Mumbai,Inactive
408,EMP10409,Bala Khan,43.0,Male,HR,82673.51,22.1,2018-09-19,4,bala.khan408@company.com,Chennai,On Leave
409,EMP10410,Vijay Iyer,28.0,Female,IT,37510.88,8.2,2017-06-12,2,vijay.iyer409@company.com,Coimbatore,Inactive
410,EMP10411,Bala Singh,45.0,Male,Operations,82061.85,26.0,2015-08-23,1,bala.singh410@company.com,Mumbai,Inactive
411,EMP10412,Sanjay Nair,39.0,Female,HR,59376.04,16.5,2024-11-08,3,sanjay.nair411@company.com,Hyderabad,Active
412,EMP10413,Rahul Khan,22.0,Female,HR,67794.2,16.6,2017-08-14,3,rahul.khan412@company.com,Mumbai,Inactive
413,EMP10414,Arun Reddy,41.0,Male,Finance,44664.29,18.1,2020-01-14,1,arun.reddy413@company.com,Chennai,On Leave
414,EMP10415,Vijay Raj,29.0,Male,HR,28488.53,3.8,2024-07-21,5,vijay.raj414@company.com,Hyderabad,Inactive
985,EMP10401,Rahul Das,40.0,Female,IT,107911.61,3.9,2020-05-04,1,rahul.das400@company.com,Chennai,Inactive
986,EMP10402,Kavin Nair,51.0,Male,Finance,29381.74,19.9,2018-09-14,3,kavin.nair401@company.com,Bengaluru,Inactive
987,EMP10403,Meena Das,56.0,Male,Operations,46503.39,25.6,2023-04-27,4,meena.das402@company.com,Coimbatore,Active
988,EMP10404,Rahul Patel,49.0,Female,IT,105965.07,23.4,2020-09-24,5,rahul.patel403@company.com,Hyderabad,On Leave
989,EMP10405,Bala Patel,51.0,Male,Finance,65772.35,9.4,2016-05-21,5,bala.patel404@company.com,Mumbai,Active
990,EMP10406,Divya Nair,41.0,Female,IT,45921.4,17.1,2019-09-09,4,divya.nair405@company.com,Hyderabad,On Leave
991,EMP10407,Priya Iyer,56.0,Male,Sales,103782.25,30.8,2015-08-13,4,priya.iyer406@company.com,Mumbai,On Leave
992,EMP10408,Kavin Khan,33.0,Female,HR,69121.16,4.8,2017-10-20,5,kavin.khan407@company.com,Mumbai,Inactive
993,EMP10409,Bala Khan,43.0,Male,HR,82673.51,22.1,2018-09-19,4,bala.khan408@company.com,Chennai,On Leave
994,EMP10410,Vijay Iyer,28.0,Female,IT,37510.88,8.2,2017-06-12,2,vijay.iyer409@company.com,Coimbatore,Inactive
995,EMP10411,Bala Singh,45.0,Male,Operations,82061.85,26.0,2015-08-23,1,bala.singh410@company.com,Mumbai,Inactive
996,EMP10412,Sanjay Nair,39.0,Female,HR,59376.04,16.5,2024-11-08,3,sanjay.nair411@company.com,Hyderabad,Active
997,EMP10413,Rahul Khan,22.0,Female,HR,67794.2,16.6,2017-08-14,3,rahul.khan412@company.com,Mumbai,Inactive
998,EMP10414,Arun Reddy,41.0,Male,Finance,44664.29,18.1,2020-01-14,1,arun.reddy413@company.com,Chennai,On Leave
999,EMP10415,Vijay Raj,29.0,Male,HR,28488.53,3.8,2024-07-21,5,vijay.raj414@company.com,Hyderabad,Inactive

**Interpretation**

- The output displays all rows that are completely duplicated.
- All column values in these rows are the same.

## **2.4 Potential Duplicate Records**



**Understand the Concept**

Potential duplicate records are records that may represent the same person but are not completely identical.

**Demonstrate the Concept**

Two records may have the same Name, Email, and other details but different EmployeeID values.


**Real-Life Example**

The same employee may be entered twice with different EmployeeID values due to a data entry mistake.

**AI/ML Usage**

Potential duplicates can create repeated information and affect data analysis and Machine Learning results.

In [44]:
# potential duplicates based on employee details
potential_duplicates = df[df.duplicated(subset=["Name", "Email"],keep=False)]
potential_duplicates

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
300,EMP10301,Divya Patel,58.0,Female,Sales,62149.06,17.5,2015-10-06,2,divya.patel300@company.com,Chennai,On Leave
301,EMP10302,Kavin Khan,56.0,Male,Sales,89058.86,18.6,2020-03-16,4,kavin.khan301@company.com,Coimbatore,On Leave
302,EMP10303,Sanjay Das,35.0,Male,HR,32687.33,14.1,2016-11-02,3,sanjay.das302@company.com,Mumbai,On Leave
303,EMP10304,Priya Nair,39.0,Female,HR,115945.67,20.1,2024-09-02,1,priya.nair303@company.com,Pune,Inactive
304,EMP10305,Meena Kumar,54.0,Male,Finance,112661.93,17.0,2020-04-03,3,meena.kumar304@company.com,Chennai,Inactive
400,EMP10401,Rahul Das,40.0,Female,IT,107911.61,3.9,2020-05-04,1,rahul.das400@company.com,Chennai,Inactive
401,EMP10402,Kavin Nair,51.0,Male,Finance,29381.74,19.9,2018-09-14,3,kavin.nair401@company.com,Bengaluru,Inactive
402,EMP10403,Meena Das,56.0,Male,Operations,46503.39,25.6,2023-04-27,4,meena.das402@company.com,Coimbatore,Active
403,EMP10404,Rahul Patel,49.0,Female,IT,105965.07,23.4,2020-09-24,5,rahul.patel403@company.com,Hyderabad,On Leave
404,EMP10405,Bala Patel,51.0,Male,Finance,65772.35,9.4,2016-05-21,5,bala.patel404@company.com,Mumbai,Active
405,EMP10406,Divya Nair,41.0,Female,IT,45921.4,17.1,2019-09-09,4,divya.nair405@company.com,Hyderabad,On Leave
406,EMP10407,Priya Iyer,56.0,Male,Sales,103782.25,30.8,2015-08-13,4,priya.iyer406@company.com,Mumbai,On Leave
407,EMP10408,Kavin Khan,33.0,Female,HR,69121.16,4.8,2017-10-20,5,kavin.khan407@company.com,Mumbai,Inactive
408,EMP10409,Bala Khan,43.0,Male,HR,82673.51,22.1,2018-09-19,4,bala.khan408@company.com,Chennai,On Leave
409,EMP10410,Vijay Iyer,28.0,Female,IT,37510.88,8.2,2017-06-12,2,vijay.iyer409@company.com,Coimbatore,Inactive
410,EMP10411,Bala Singh,45.0,Male,Operations,82061.85,26.0,2015-08-23,1,bala.singh410@company.com,Mumbai,Inactive
411,EMP10412,Sanjay Nair,39.0,Female,HR,59376.04,16.5,2024-11-08,3,sanjay.nair411@company.com,Hyderabad,Active
412,EMP10413,Rahul Khan,22.0,Female,HR,67794.2,16.6,2017-08-14,3,rahul.khan412@company.com,Mumbai,Inactive
413,EMP10414,Arun Reddy,41.0,Male,Finance,44664.29,18.1,2020-01-14,1,arun.reddy413@company.com,Chennai,On Leave
414,EMP10415,Vijay Raj,29.0,Male,HR,28488.53,3.8,2024-07-21,5,vijay.raj414@company.com,Hyderabad,Inactive
980,EMPX301,Divya Patel,58.0,Female,Sales,62149.06,17.5,2015-10-06,2,divya.patel300@company.com,Chennai,On Leave
981,EMPX302,Kavin Khan,56.0,Male,Sales,89058.86,18.6,2020-03-16,4,kavin.khan301@company.com,Coimbatore,On Leave
982,EMPX303,Sanjay Das,35.0,Male,HR,32687.33,14.1,2016-11-02,3,sanjay.das302@company.com,Mumbai,On Leave
983,EMPX304,Priya Nair,39.0,Female,HR,115945.67,20.1,2024-09-02,1,priya.nair303@company.com,Pune,Inactive
984,EMPX305,Meena Kumar,54.0,Male,Finance,112661.93,17.0,2020-04-03,3,meena.kumar304@company.com,Chennai,Inactive
985,EMP10401,Rahul Das,40.0,Female,IT,107911.61,3.9,2020-05-04,1,rahul.das400@company.com,Chennai,Inactive
986,EMP10402,Kavin Nair,51.0,Male,Finance,29381.74,19.9,2018-09-14,3,kavin.nair401@company.com,Bengaluru,Inactive
987,EMP10403,Meena Das,56.0,Male,Operations,46503.39,25.6,2023-04-27,4,meena.das402@company.com,Coimbatore,Active
988,EMP10404,Rahul Patel,49.0,Female,IT,105965.07,23.4,2020-09-24,5,rahul.patel403@company.com,Hyderabad,On Leave
989,EMP10405,Bala Patel,51.0,Male,Finance,65772.35,9.4,2016-05-21,5,bala.patel404@company.com,Mumbai,Active
990,EMP10406,Divya Nair,41.0,Female,IT,45921.4,17.1,2019-09-09,4,divya.nair405@company.com,Hyderabad,On Leave
991,EMP10407,Priya Iyer,56.0,Male,Sales,103782.25,30.8,2015-08-13,4,priya.iyer406@company.com,Mumbai,On Leave
992,EMP10408,Kavin Khan,33.0,Female,HR,69121.16,4.8,2017-10-20,5,kavin.khan407@company.com,Mumbai,Inactive
993,EMP10409,Bala Khan,43.0,Male,HR,82673.51,22.1,2018-09-19,4,bala.khan408@company.com,Chennai,On Leave
994,EMP10410,Vijay Iyer,28.0,Female,IT,37510.88,8.2,2017-06-12,2,vijay.iyer409@company.com,Coimbatore,Inactive
995,EMP10411,Bala Singh,45.0,Male,Operations,82061.85,26.0,2015-08-23,1,bala.singh410@company.com,Mumbai,Inactive
996,EMP10412,Sanjay Nair,39.0,Female,HR,59376.04,16.5,2024-11-08,3,sanjay.nair411@company.com,Hyderabad,Active
997,EMP10413,Rahul Khan,22.0,Female,HR,67794.2,16.6,2017-08-14,3,rahul.khan412@company.com,Mumbai,Inactive
998,EMP10414,Arun Reddy,41.0,Male,Finance,44664.29,18.1,2020-01-14,1,arun.reddy413@company.com,Chennai,On Leave
999,EMP10415,Vijay Raj,29.0,Male,HR,28488.53,3.8,2024-07-21,5,vijay.raj414@company.com,Hyderabad,Inactive

**Interpretation**

- The output displays records with the same Name and Email.
- These records may represent the same employee.
- They should be reviewed to confirm whether they are actual duplicates.

## **3. Invalid Values**

## **3.1 Negative Values**

**Understand the Concept**

Negative values are numbers below zero that may not be valid for certain columns.

**Demonstrate the Concept**

Columns such as Age, Salary, and Experience should not normally contain negative values.


**Real-Life Example**

An employee cannot have an age of -5 or a salary of -10,000.

**AI/ML Usage**

Invalid negative values can affect data analysis and Machine Learning models.

In [45]:
# negative values in Age, Salary, and Experience
negative_values = df[(pd.to_numeric(df["Age"], errors="coerce") < 0) |
                     (pd.to_numeric(df["Salary"], errors="coerce") < 0) |
                     (pd.to_numeric(df["Experience"], errors="coerce") < 0)]
negative_values

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
250,EMP10251,Divya Sharma,-5.0,Male,Sales,58889.55,18.7,2015-01-24,4,divya.sharma250@company.com,Mumbai,On Leave
252,EMP10253,Arun Reddy,30.0,Female,HR,-10000.0,32.8,2015-07-03,5,arun.reddy252@company.com,Hyderabad,Active
253,EMP10254,Vijay Reddy,26.0,Female,Marketing,34814.35,-3.0,2024-04-21,2,vijay.reddy253@company.com,Hyderabad,On Leave

**Interpretation**

- The output displays records with invalid negative values.
- Negative values are present in columns where they are not appropriate.

## **3.2 Impossible Values**



**Understand the Concept**

Impossible values are values that are outside the valid or expected range.

**Demonstrate the Concept**

For example, an employee cannot normally have an age of 150, 90 years of experience, or a performance score of 10 when the valid score is from 1 to 5.

**Real-Life Example**

An employee with 150 years of age is an impossible value and indicates a data quality issue.

**AI/ML Usage**

Impossible values can affect data analysis and Machine Learning results.

In [46]:
# Convert columns to numeric values
age = pd.to_numeric(df["Age"], errors="coerce")
experience = pd.to_numeric(df["Experience"], errors="coerce")
performance = pd.to_numeric(df["PerformanceScore"], errors="coerce")

# impossible values
impossible_values = df[(age > 100)|(experience > 50)|(performance < 1)|(performance > 5)]
impossible_values

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
251,EMP10252,Sanjay Iyer,150.0,Female,Operations,107100.54,19.5,2025-04-18,2,sanjay.iyer251@company.com,Bengaluru,Active
254,EMP10255,Meena Raj,45.0,Male,Sales,90166.93,90.0,2023-02-25,3,meena.raj254@company.com,Chennai,Inactive
255,EMP10256,Vijay Nair,44.0,Female,Operations,88352.1,4.9,2018-02-10,10,vijay.nair255@company.com,Bengaluru,Active
256,EMP10257,Bala Singh,29.0,Male,Sales,117141.64,3.3,2022-06-05,0,bala.singh256@company.com,Mumbai,Inactive

**Interpretation**

- The output displays records with impossible values.
- These values are outside the expected range.

## **3.3 Incorrect Categories**



**Understand the Concept**

Incorrect categories are values that do not belong to the expected categories of a column.

**Demonstrate the Concept**

For example, the Gender column may be expected to contain only Male or Female.



**Real-Life Example**

If Gender contains values such as M, Other, or Not Available, these can be treated as incorrect or unexpected categories based on the dataset rules.

**AI/ML Usage**

Incorrect categories can create errors during data analysis and encoding.

In [47]:
# incorrect values in Gender col
valid_gender = ["Male", "Female"]

incorrect_categories = df[~df["Gender"].isin(valid_gender)]
incorrect_categories

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
234,EMP10235,Bala Reddy,35.0,Not Available,Finance,32754.85,2.1,2021-12-13,1,bala.reddy234@company.com,Pune,Inactive
240,EMP10241,Bala Sharma,53.0,Other,Operations,80865.55,1.0,2016-04-02,2,bala.sharma240@company.com,Pune,Active
241,EMP10242,Sanjay Singh,57.0,M,Sales,65063.49,9.7,2017-10-22,5,sanjay.singh241@company.com,Hyderabad,Inactive

**Interpretation**

- The output displays records with incorrect Gender categories.
- These values do not match the expected categories.

## **3.4 Invalid Dates**



**Understand the Concept**

Invalid dates are dates that do not follow a valid date format or do not exist.

**Demonstrate the Concept**

For example, 2025-13-40 and 2024-02-30 are invalid dates.

**Real-Life Example**

An employee joining date must be a valid calendar date. A date with an invalid month or day indicates a data quality issue.

**AI/ML Usage**

Invalid dates can cause errors during data processing and feature creation.

In [48]:
# Convert JoiningDate to datetime
joining_date = pd.to_datetime( df["JoiningDate"],errors="coerce")

# invalid dates
invalid_dates = df[joining_date.isnull()]
invalid_dates

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
260,EMP10261,Bala Sharma,49.0,Male,Finance,40132.31,21.2,2025-13-40,1,bala.sharma260@company.com,Coimbatore,Active
261,EMP10262,Bala Sharma,34.0,Female,Operations,99326.62,19.8,invalid-date,2,bala.sharma261@company.com,Hyderabad,Inactive
262,EMP10263,Vijay Khan,59.0,Male,Finance,56068.15,23.4,2024-02-30,5,vijay.khan262@company.com,Pune,Inactive

## **3.5 Incorrect Data Types**



**Understand the Concept**

Incorrect data types occur when a column contains a value with an unsuitable data type.

**Demonstrate the Concept**

For example, Age should contain numbers, but a value such as Thirty is text.

**Real-Life Example**

Salary and Experience should contain numerical values. Text values in these columns can cause data quality issues.

**AI/ML Usage**

Incorrect data types can cause errors during data analysis and Machine Learning.

In [49]:
# Convert expected numerical columns
age = pd.to_numeric(df["Age"], errors="coerce")
salary = pd.to_numeric(df["Salary"], errors="coerce")
experience = pd.to_numeric(df["Experience"], errors="coerce")

# rows with incorrect data types
incorrect_data_types = df[age.isnull() | salary.isnull() | experience.isnull()]
incorrect_data_types

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
10,EMP10011,Arun Singh,NaN,Male,Finance,61924.34,9.5,2019-08-26,1,arun.singh10@company.com,Chennai,Active
15,EMP10016,Naveen Kumar,56.0,Female,IT,NaN,9.6,2017-01-03,5,naveen.kumar15@company.com,Chennai,Inactive
25,EMP10026,Arun Patel,NaN,Male,Marketing,72754.51,1.8,2019-01-01,3,arun.patel25@company.com,Coimbatore,On Leave
50,EMP10051,Kavin Reddy,NaN,Male,HR,81129.16,1.1,2018-10-06,3,kavin.reddy50@company.com,Mumbai,Active
60,EMP10061,Meena Khan,31.0,Male,IT,NaN,31.0,2018-10-26,3,meena.khan60@company.com,Pune,Inactive
100,EMP10101,Sanjay Nair,NaN,Female,Sales,82768.35,22.3,2025-03-02,4,sanjay.nair100@company.com,Chennai,Active
120,EMP10121,Divya Reddy,32.0,Female,IT,NaN,28.6,2015-08-06,3,divya.reddy120@company.com,Pune,On Leave
150,EMP10151,Meena Sharma,NaN,Female,HR,64389.29,3.0,2022-01-07,1,meena.sharma150@company.com,Chennai,Active
270,EMP10271,Sanjay Sharma,Thirty,Female,HR,43598.91,0.3,2019-12-15,1,sanjay.sharma270@company.com,Coimbatore,On Leave
271,EMP10272,Rahul Iyer,57.0,Female,Marketing,Unknown,2.1,2019-06-19,2,rahul.iyer271@company.com,Mumbai,Active
272,EMP10273,Naveen Patel,35.0,Male,Sales,71157.82,Five,2018-11-15,4,naveen.patel272@company.com,Hyderabad,Inactive

**Interpretation**

- The output displays records with possible incorrect data types.
- Text values are present in columns expected to contain numbers.

## **3.6 Unexpected Values**



**Understand the Concept**

Unexpected values are values that do not match the expected data or format.

**Demonstrate the Concept**

For example, the Status column is expected to contain Active, Inactive, or On Leave. Other values are unexpected.

**Real-Life Example**

If an employee status contains Working instead of the expected categories, it is an unexpected value.

**AI/ML Usage**

Unexpected values can affect data analysis and Machine Learning results.

In [50]:
# expected values
valid_status = ["Active", "Inactive", "On Leave"]

# Find unexpected values
unexpected_values = df[~df["Status"].isin(valid_status)]
unexpected_values

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
233,EMP10234,Naveen Sharma,41.0,Female,Marketing,77535.14,20.9,2020-10-03,1,naveen.sharma233@company.com,Chennai,NaN
243,EMP10244,Arun Sharma,29.0,Male,IT,63504.47,21.1,2024-12-14,2,arun.sharma243@company.com,Mumbai,Working

**Interpretation**

- The output displays records with unexpected Status values.
- These values do not match the expected categories.

## **3.7 Empty Strings**



**Understand the Concept**

Empty strings are text values that contain no information.

**Demonstrate the Concept**

An empty string may appear as a blank value in a text column.


**Real-Life Example**

An employee Name or City field may be left blank during data entry.

**AI/ML Usage**

Empty strings can affect data analysis and Machine Learning.

In [51]:
# rows containing empty strings
empty_strings = df[df.select_dtypes(include="object").eq("").any(axis=1)]
empty_strings

Empty DataFrame
Columns: [EmployeeID, Name, Age, Gender, Department, Salary, Experience, JoiningDate, PerformanceScore, Email, City, Status]
Index: []

**Interpretation**

- The output displays rows containing empty strings.
- Empty strings represent missing or unavailable text data.

## **3.8 Null-Like Values**



**Understand the Concept**

Null-like values are text values that represent missing or unavailable data.

**Demonstrate the Concept**

Common null-like values include NA, N/A, NULL, None, and Unknown.


**Real-Life Example**

An employee Department may contain N/A instead of an actual department name.

**AI/ML Usage**

Null-like values should be identified and converted to proper missing values before data analysis & Machine Learning.

In [52]:
# common null-like values
null_like_values = ["NA", "N/A", "NULL", "None", "Unknown"]

# rows containing null-like values
null_like_rows = df[ df.astype(str).isin(null_like_values).any(axis=1)]
null_like_rows

,EmployeeID,Name,Age,Gender,Department,Salary,Experience,JoiningDate,PerformanceScore,Email,City,Status
232,EMP10233,Bala Raj,33.0,Male,Unknown,107742.07,25.0,2018-11-07,3,bala.raj232@company.com,Chennai,Inactive
271,EMP10272,Rahul Iyer,57.0,Female,Marketing,Unknown,2.1,2019-06-19,2,rahul.iyer271@company.com,Mumbai,Active

**Interpretation**

- The output displays rows containing null-like values.
- These values represent missing or unavailable information.